public with sharing class SalesforceDeveloper2 {
    public void myFirstCode2() {
        System.debug('Esaretin Bedeli');
        System.debug('Kutahya');
        System.debug('Ilkbahar');
    }
    public void MyFavorites(){
        String sehir = 'Istanbul';
        System.debug(sehir);
        Integer sayi = 25;
        System.debug(sayi);
        String result = 'Favori numaram -> ' + sayi +' ve Favori şehrim -> '+ sehir;
        System.debug(result);
        
    }
}